name: Rizzsist
options:
  bundleIdPrefix: com.rizzsist
  deploymentTarget: 15.0
settings:
  CODE_SIGN_STYLE: Automatic
  CODE_SIGNING_ALLOWED: YES
  DEVELOPMENT_TEAM: ""
targets:
  Rizzsist:
    type: application
    platform: iOS
    sources:
      - path: Rizzsist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.rizzsist.app
  RizzsistKeyboard:
    type: app-extension
    platform: iOS
    sources:
      - path: RizzsistKeyboard
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.rizzsist.app.keyboard
